#!/bin/bash
# Name "influxsend" Copyright (c) Cybera

now=$(date)

echo "$now  influxsend run" >> /debug/logfile

#mkdir /tmp/runfiles/tmp
#cd /tmp/runfiles/tmp
#/tmp/runfiles/./timer.pl 30 /tmp/runfiles/./Sendinflux.pl
#echo "$now  tmp created and ./Sendinflux.pl run" >> /debug/logfile

mkdir /tmp/runfiles/tmp2
cd /tmp/runfiles/tmp2
/tmp/runfiles/./timer.pl 30 /tmp/runfiles/./SendINT.pl #& /tmp/runfiles/./Sendinflux.pl
echo "$now  tmp2 created ./timer.pl and ./SendINT.pl and ./Sendinflux.pl run" >> /debug/logfile
