FROM tatianameleshko/ubuntu_odbc:latest

RUN pip3 install jupyter==1.0.0 plotly==4.4.1 chart_studio==1.0.0 scipy==1.4.1 sklearn==0.0 matplotlib==3.1.2

RUN pip3 install dash==1.8.0 dash_auth==1.3.2 dash-renderer==1.2.3 dash-core-components==1.7.0 dash-html-components==1.0.2 dash-table-experiments==0.6.0 

RUN mkdir /dashboard

WORKDIR /dashboard

ADD data_analysis/Dashboard ./

CMD ["python3", "./connectin_dashboard.py"]

