version: "3"

services:
  webserver:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-webserver
    ports:
      - "80:80"
    volumes:
      - /usr/local/apache2:/ConnectedMB/server/serverfiles/www
