version: "3"

services:
  webserver:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-webserver
    ports:
      - "80:80"
    volumes:
      - /ConnectedMB/server/serverfiles/www:/var/www/html
