version: "3"

services:
  influxdb:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-influxdb
    env_file:
      - creds.env
    ports:
      - "8086:8086"
    volumes:
      - ./utils/influxdb.conf:/etc/influxdb/influxdb.conf
      - ./:/home/connectin
  cronjobs:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-cronjobs
    env_file:
      - creds.env
    volumes:
      - ./:/home/connectin 
  jupyter:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-jupyter
    env_file:
      - creds.env
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/connectin
  dash:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-dashboard
    env_file:
      - creds.env
    ports:
      - "8050:8050"
    volumes:
      - ./:/home/connectin
  webserver:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-webserver
    ports:
      - "80:80"
    volumes:
      - /ConnectedMB/server/serverfiles/www:/usr/share/nginx/html
      

version: "2.1"
services:
  librespeed:
    image: ghcr.io/linuxserver/librespeed
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=PASSWORD
      - CUSTOM_RESULTS=true #optional
      - DB_TYPE=sqlite #optional
      - DB_NAME=DB_NAME #optional
      - DB_HOSTNAME=DB_HOSTNAME #optional
      - DB_USERNAME=DB_USERNAME #optional
      - DB_PASSWORD=DB_PASSWORD #optional
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 8081:8081
    restart: unless-stopped
