#!/usr/bin/env bash
# This script runs on reboot to copy the project files to the
# temporary directory and start data collection
# Name:"copytotmp" Copyright (c) Joel Templeman 2020

mkdir /tmp/runfiles
cp -rf /runfiles/* /tmp/runfiles
echo "Runfiles Copied"

./tmp/runfiles/influxsend
echo "influxsend run"

echo "Complete. Rules copied to /tmp & started"
