#!/usr/bin/env bash
# This script runs on reboot to copy the project files to the
# temporary directory and start data collection
# Name:"copytotmp" Copyright (c) Joel Templeman 2020

function make_copy {

	mkdir /tmp/runfiles
	cp -rf /runfiles/* /tmp/runfiles
	echo "Runfiles Copied"

	./tmp/runfiles/influxsend
	echo "influxsend called"

	echo "Complete. Rules copied to /tmp & started"

}

echo "copytotmp"

if [ -d /tmp/runfiles ]; then

	echo "Already there"
	rm -rf /tmp/runfiles/*
	rmdir /tmp/runfiles
	echo "Deleted"

	make_copy
else
	make_copy
fi

echo "Script Complete"
