#!/usr/bin/env bash
# Script to copy files from USB to OpenWrt device
# Name: "firstcopy" Copyright (c) Joel Templeman 2020

now=$(date)

# Find USB mount folder
path=$(ls -a */sda*)
echo $now > /pathlocation
echo $path >> /pathlocation

function make_copy {

	#Make a logfile for debugging
		mkdir /debug
		echo "$now  Logfile Created by firstcopy script" > /debug/logfile
	#Make a folder for the project files and copy them from USB
        	mkdir /runfiles /runfiles/CSV /runfiles/CSV-INT
        	cp -rf /mnt/sda1/runfiles/* /runfiles
        	echo "$now  Runfiles copied" >> /debug/logfile

        #Copy custom files over to specific locations
	        \cp -f /mnt/sda1/scripts/dropbear /etc/config
        	\cp -f /mnt/sda1/scripts/BannerFile /etc
        	\cp -f /mnt/sda1/scripts/banner /etc
		\cp -f /mnt/sda1/scripts/copytotmp /
        	chmod +x /copytotmp
		\cp -f /etc/rc.local /etc/rc.local.bak
		\cp -f /mnt/sda1/scripts/rc.local /etc/rc.local
		\cp -f /mnt/sda1/runfiles/Ping.pm /usr/lib/perl5/5.28/
		echo "$now  Custom scripts copied" >> /debug/logfile	
	
	echo "$now  Function works" >> /debug/logfile

}	

echo "$now  firstcopy complete" >> /debug/logfile

if [ -d /runfiles ]; then

	echo "Already there"
	rm -r /runfiles/*
	rmdir /runfiles
	echo "Deleted" 

        make_copy
else
	make_copy
fi

/etc/init.d/dropbear restart
echo "Script Complete"
