#!/usr/bin/env bash
# Script to copy files from USB to OpenWrt device
# Name: "firstcopy" Copyright (c) Joel Templeman 2020

now=$(date)	# Get current date/time
#echo "IP Address of host server: "  
#read IP_Address

function make_copy {

	#Make a logfile for debugging
		mkdir /debug
		echo "$now  Logfile Created by firstcopy script" > /debug/logfile
	#Make a folder for the project files and copy them from USB
        	mkdir /runfiles /runfiles/CSV /runfiles/CSV-INT
        	cp -rf /tmp/packages/monitor/runfiles/* /runfiles
        	echo "$now  Runfiles copied" >> /debug/logfile

        #Copy custom files over to specific locations
	        \cp -f /tmp/packages/monitor/scripts/dropbear /etc/config
        	\cp -f /tmp/packages/monitor/scripts/BannerFile /etc
        	\cp -f /tmp/packages/monitor/scripts/banner /etc
		\cp -f /tmp/packages/monitor/scripts/copytotmp /
        	chmod +x /copytotmp
		\cp -f /etc/rc.local /etc/rc.local.bak
		\cp -f /tmp/packages/monitor/scripts/rc.local /etc/rc.local
		\cp -f /tmp/packages/monitor/runfiles/Ping.pm /usr/lib/perl5/5.28/
		echo "$now  Custom scripts copied" >> /debug/logfile	
	
	echo "$now  firstcopy complete" >> /debug/logfile

}	


# This is only needed for development. In production this should be a one time process. 
# This is only otherwise needed if the user accidently runs the script more than once.

if [ -d /runfiles ]; then

	echo "Already there"
	rm -r /runfiles/*
	rmdir /runfiles
		if [ -d /debug ]; then
			rm /debug/logfile
			rmdir /debug
		fi
	echo "Deleted" 

        make_copy
else
	make_copy
fi

/etc/init.d/dropbear restart
echo "$now Firstcopy Script EOF" >> /debug/logfile
